api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Upwork/Entity', '%kernel.project_dir%/src/Domain/Core/Entity']
    enable_swagger_ui: false
    enable_re_doc: false
    enable_swagger: false
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        \DomainException: 400
